spring.application.name=InfluenceNet

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/influencenet
spring.datasource.username=influencenet_user
spring.datasource.password=influencenet_pass
spring.datasource.hikari.maximum-pool-size=10

# MongoDB
spring.data.mongodb.uri=mongodb://admin:admin_pass@localhost:27017/influencenet?authSource=admin

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redis_pass

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200

# Neo4j
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=neo4j_password
